"""empty message

Revision ID: c24f4c7c96c7
Revises: 43ca0788be18
Create Date: 2021-06-26 07:30:19.757979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c24f4c7c96c7'
down_revision = '43ca0788be18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('second_gen', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('second_gen_ibfk_1', 'second_gen', type_='foreignkey')
    op.create_foreign_key(None, 'second_gen', 'first_gen', ['owner_id'], ['id'])
    op.drop_column('second_gen', 'second_gen_id')
    op.drop_constraint('third_gen_ibfk_1', 'third_gen', type_='foreignkey')
    op.drop_column('third_gen', 'third_gen_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('third_gen', sa.Column('third_gen_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('third_gen_ibfk_1', 'third_gen', 'second_gen', ['third_gen_id'], ['id'])
    op.add_column('second_gen', sa.Column('second_gen_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'second_gen', type_='foreignkey')
    op.create_foreign_key('second_gen_ibfk_1', 'second_gen', 'first_gen', ['second_gen_id'], ['id'])
    op.drop_column('second_gen', 'owner_id')
    # ### end Alembic commands ###
