"""empty message

Revision ID: ebfb8be61c5f
Revises: c24f4c7c96c7
Create Date: 2021-06-26 07:34:27.303780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebfb8be61c5f'
down_revision = 'c24f4c7c96c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('second_gen', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint('second_gen_ibfk_1', 'second_gen', type_='foreignkey')
    op.create_foreign_key(None, 'second_gen', 'first_gen', ['parent_id'], ['id'])
    op.drop_column('second_gen', 'owner_id')
    op.add_column('third_gen', sa.Column('grandparent_id', sa.Integer(), nullable=True))
    op.add_column('third_gen', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'third_gen', 'second_gen', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'third_gen', 'first_gen', ['grandparent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'third_gen', type_='foreignkey')
    op.drop_constraint(None, 'third_gen', type_='foreignkey')
    op.drop_column('third_gen', 'parent_id')
    op.drop_column('third_gen', 'grandparent_id')
    op.add_column('second_gen', sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'second_gen', type_='foreignkey')
    op.create_foreign_key('second_gen_ibfk_1', 'second_gen', 'first_gen', ['owner_id'], ['id'])
    op.drop_column('second_gen', 'parent_id')
    # ### end Alembic commands ###
